# Generated by Django 3.1.3 on 2020-11-07 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20201105_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
