# Generated by Django 3.1.3 on 2020-11-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_tasklist_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
